name: 'Avoid workflow being suspended'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 13 * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      
      - name: 'Avoid Github Workflow being suspended'
        run: echo $(cat /proc/sys/kernel/random/uuid) > demo.txt
      
      - name: 'Commit Files'
        id: commit
        run: |
          git config --local user.email "action@gmail.com"
          git config --local user.name "g00gle"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'avoid being suspended'
          echo ::set-output name=status::success
           
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
